version: '3.8'

services:
  general-server:
    build:
      context: .
      dockerfile: Dockerfile.general
    container_name: rubin-general-server
    ports:
      - "8085:8085"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - rubin-network

networks:
  rubin-network:
    driver: bridge



