version: '3.8'

services:
  controllers-server:
    build: .
    container_name: rubin-controllers-server
    ports:
      - "9000:8086"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      # Монтируем директорию для доступа к PLC файлам
      - ./plc_files:/app/plc_files:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rubin-network

networks:
  rubin-network:
    driver: bridge