app = "rubin-ai-v2"
primary_region = "fra"

[build]

[env]
  PORT = "8080"
  QDRANT_URL = "https://your-qdrant.fly.dev"
  LOCALAI_URL = "https://your-localai.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
